package com.lc.dao;

import com.lc.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product product);
    /*
     * 产品上下架
     * */
    int updateByPrimaryKeytoStatus(Product record);

    /*
     * 后台-产品搜索
     * */
    List<Product> selectByIdOrName(@Param("productId") Integer productId,
                                   @Param("productName") String productName);

    /*
     * 产品搜索及动态排序List
     * */
    List<Product> searchProduct(@Param("integers")Set<Integer> integers,
                                @Param("keyword")String keyword);
}